#############################################################################
# Makefile for building: script-editor.app/Contents/MacOS/script-editor
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  script-editor.pro
# Template: app
# Command: /Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/qmake -o Makefile script-editor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang -F/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib
QMAKE         = /Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = script-editor1.0.0
DISTDIR = /Users/Thomas/Documents/College/Career/Projects/pkmn/script-editor/.tmp/script-editor1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		document.cpp \
		theme.cpp \
		project.cpp moc_mainwindow.cpp \
		moc_document.cpp
OBJECTS       = main.o \
		mainwindow.o \
		document.o \
		theme.o \
		project.o \
		moc_mainwindow.o \
		moc_document.o
DIST          = /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resources.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/moc.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/uic.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		script-editor.pro mainwindow.h \
		document.h \
		theme.h \
		project.h main.cpp \
		mainwindow.cpp \
		document.cpp \
		theme.cpp \
		project.cpp
QMAKE_TARGET  = script-editor
DESTDIR       = 
TARGET        = script-editor.app/Contents/MacOS/script-editor

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d script-editor.app/Contents/MacOS/ || mkdir -p script-editor.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: script-editor.pro /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resources.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/moc.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/uic.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		script-editor.pro \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile script-editor.pro
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qdevice.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/device_config.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/unix.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/mac.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/macx.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/qconfig.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/default_post.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qt.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/resources.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/moc.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/uic.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/yacc.prf:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/lex.prf:
script-editor.pro:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile script-editor.pro

qmake_all: FORCE

script-editor.app/Contents/PkgInfo: 
	@test -d script-editor.app/Contents || mkdir -p script-editor.app/Contents
	@$(DEL_FILE) script-editor.app/Contents/PkgInfo
	@echo "APPL????" > script-editor.app/Contents/PkgInfo
script-editor.app/Contents/Resources/empty.lproj: 
	@test -d script-editor.app/Contents/Resources || mkdir -p script-editor.app/Contents/Resources
	@touch script-editor.app/Contents/Resources/empty.lproj
	
script-editor.app/Contents/Info.plist: 
	@test -d script-editor.app/Contents || mkdir -p script-editor.app/Contents
	@$(DEL_FILE) script-editor.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Thomas.script-editor,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Thomas.script-editor,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,script-editor,g" -e "s,@LIBRARY@,script-editor,g" -e "s,\$${EXECUTABLE_NAME},script-editor,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang/Info.plist.app >script-editor.app/Contents/Info.plist

all: Makefile \
		script-editor.app/Contents/PkgInfo \
		script-editor.app/Contents/Resources/empty.lproj \
		script-editor.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h document.h theme.h project.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp document.cpp theme.cpp project.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r script-editor.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h /Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_document.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_document.cpp
moc_mainwindow.cpp: /Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		document.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		mainwindow.h \
		moc_predefs.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/moc
	/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/Thomas/Documents/College/Career/Projects/pkmn/script-editor -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_document.cpp: /Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		document.h \
		moc_predefs.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/moc
	/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/mkspecs/macx-clang -I/Users/Thomas/Documents/College/Career/Projects/pkmn/script-editor -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers -I/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib document.h -o moc_document.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/uic
	/Users/Thomas/Applications/Qt/5.11.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		document.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		document.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		ui_mainwindow.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

document.o: document.cpp document.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/QPlainTextEdit \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o document.cpp

theme.o: theme.cpp theme.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o theme.o theme.cpp

project.o: project.cpp project.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QVector \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/QMap \
		/Users/Thomas/Applications/Qt/5.11.1/clang_64/lib/QtCore.framework/Headers/qmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o project.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_document.o: moc_document.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_document.o moc_document.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

